version: "3"

services:
  build                   :
    depends_on            :
      - mariadb
    networks              :
      - app_network       
    container_name        : build
    build                 : 
      context             : .
      dockerfile          : Dockerfile
      target              : build

  runtime                 :
    networks              :
     - app_network       
    container_name        : runtime
    build                 : 
      context             : .
      dockerfile          : Dockerfile
      target              : runtime
    ports                 :
      - "9999:80"
    depends_on            :
      - build

  mariadb                 :
    container_name        : mariadb
    image                 : niba291/ejercicio_3_databases
    restart               : always
    environment           : 
      MYSQL_ROOT_PASSWORD : 12345
      MYSQL_DATABASE      : ejercicio_3
    volumes               :
      - ./databases:/var/lib/mysql
    networks              :
      - app_network
    ports                 :
      - "127.0.0.1:9001:3306"

networks                  :
  app_network             :
    driver                : bridge
